import { invoke } from "@tauri-apps/api/core";
import { useEffect, useRef, useState } from "react";
import { MapCanvas, type MapDutyPoint } from "../features/map/MapCanvas";

const navigation = ["勤務計畫", "點位", "路線", "人力配置", "路線調整", "部署表", "未實作功能"];
const pointColors = [
  { value: "red", label: "紅色" }, { value: "orange", label: "橘色" }, { value: "yellow", label: "黃色" },
  { value: "green", label: "綠色" }, { value: "blue", label: "藍色" }, { value: "purple", label: "紫色" },
];
type DutyRoute = { id: string; planId: string; routeName: string; color: string; pointIds: string[]; routeType: string; geometry?: [number, number][]; lineStyle?: "solid" | "dashed" };
type CommonRoute = { id: string; routeName: string; color: string; geometry: [number, number][] };
type Personnel = { id: string; personnelCode: string; radioCode: string; name: string; title: string; unit: string; phone: string };
type PersonnelAssignment = { id: string; planId: string; personnelId: string; dutyPointId: string | null; assignedUnit: string; assignedTitle: string };

export default function App() {
  const mapExporter = useRef<(() => string | null) | null>(null);
  const [planId, setPlanId] = useState<string | null>(null);
  const [planName, setPlanName] = useState("尚未開啟勤務計畫");
  const [newPlanName, setNewPlanName] = useState("板橋勤務計畫");
  const [message, setMessage] = useState("建立勤務計畫後，可在地圖上新增勤務點位並安排勤務路線。");
  const [points, setPoints] = useState<MapDutyPoint[]>([]);
  const [pendingCoordinate, setPendingCoordinate] = useState<{ latitude: number; longitude: number } | null>(null);
  const [pointCode, setPointCode] = useState("");
  const [pointName, setPointName] = useState("");
  const [pointColor, setPointColor] = useState("red");
  const [activeNav, setActiveNav] = useState("勤務計畫");
  const [pendingDelete, setPendingDelete] = useState<MapDutyPoint | null>(null);
  const [selectedPointId, setSelectedPointId] = useState<string | null>(null);
  const [routes, setRoutes] = useState<DutyRoute[]>([]);
  const [commonRoutes, setCommonRoutes] = useState<CommonRoute[]>([]);
  const [personnel, setPersonnel] = useState<Personnel[]>([]);
  const [personnelAssignments, setPersonnelAssignments] = useState<PersonnelAssignment[]>([]);
  const [personnelKeyword, setPersonnelKeyword] = useState("");
  const [personnelUnit, setPersonnelUnit] = useState("");
  const [personnelTitle, setPersonnelTitle] = useState("");
  const [showPersonnelLabels, setShowPersonnelLabels] = useState(false);
  const [selectedRouteId, setSelectedRouteId] = useState<string | null>(null);
  const [editingRouteId, setEditingRouteId] = useState<string | null>(null);
  const [editingRouteName, setEditingRouteName] = useState("");
  const [routeName, setRouteName] = useState("");
  const [routeColor, setRouteColor] = useState("blue");
  const [routeLineStyle, setRouteLineStyle] = useState<"solid" | "dashed" | "dotted">("solid");
  const [validationError, setValidationError] = useState("");
  const [routePointIds, setRoutePointIds] = useState<string[]>([]);
  const [isDrawingRoute, setIsDrawingRoute] = useState(false);
  const [manualVertices, setManualVertices] = useState<[number, number][]>([]);
  useEffect(() => { void invoke<Array<{ id: string; planName: string }>>("list_duty_plans").then((plans) => { const latest = plans[0]; if (latest) { setPlanId(latest.id); setPlanName(latest.planName); setMessage("已載入最近勤務計畫。點擊地圖可新增勤務點位。"); } }).catch((error) => setMessage(`無法載入勤務計畫：${String(error)}`)); }, []);
  useEffect(() => { if (planId) void invoke<MapDutyPoint[]>("list_duty_points", { planId }).then(setPoints).catch((error) => setMessage(`無法載入勤務點位：${String(error)}`)); }, [planId]);
  useEffect(() => { if (planId) void invoke<DutyRoute[]>("list_duty_routes", { planId }).then(setRoutes).catch((error) => setMessage(`無法載入勤務路線：${String(error)}`)); setSelectedRouteId(null); }, [planId]);
  useEffect(() => { void invoke<CommonRoute[]>("list_common_routes").then(setCommonRoutes).catch((error) => setMessage(`無法載入常用路線：${String(error)}`)); }, []);
  useEffect(() => { void invoke<Personnel[]>("list_personnel").then(setPersonnel).catch((error) => setMessage(`無法載入人員資料：${String(error)}`)); }, []);
  useEffect(() => { if (planId) void invoke<PersonnelAssignment[]>("list_personnel_assignments", { planId }).then(setPersonnelAssignments).catch((error) => setMessage(`無法載入人力配置：${String(error)}`)); else setPersonnelAssignments([]); }, [planId]);
  useEffect(() => {
    function handleDeleteKey(event: KeyboardEvent) {
      const target = event.target as HTMLElement | null;
      if (target?.matches("input, textarea, [contenteditable='true']") || (event.key !== "Delete" && event.key !== "Backspace")) return;
      if (isDrawingRoute && event.key === " ") { event.preventDefault(); setManualVertices((current) => current.slice(0, -1)); return; }
      if (isDrawingRoute && (event.key === "Delete" || event.key === "Backspace")) { event.preventDefault(); setManualVertices((current) => current.slice(0, -1)); return; }
      if (isDrawingRoute && event.key === "Escape") { event.preventDefault(); setManualVertices([]); setIsDrawingRoute(false); setMessage("已取消手繪路線。"); return; }
      if (isDrawingRoute && event.key === "Enter") { event.preventDefault(); setIsDrawingRoute(false); setMessage("已完成繪製；請命名後保存路線。"); return; }
      if (pendingCoordinate) { event.preventDefault(); setPendingCoordinate(null); setMessage("已取消放置暫存點位。"); return; }
      const point = points.find((item) => item.id === selectedPointId);
      if (point) { event.preventDefault(); setPendingDelete(point); }
    }
    window.addEventListener("keydown", handleDeleteKey);
    return () => window.removeEventListener("keydown", handleDeleteKey);
  }, [isDrawingRoute, pendingCoordinate, points, selectedPointId]);
  async function createPlan() { if (!newPlanName.trim()) { setValidationError("請輸入勤務計畫名稱。"); return; } try { const plan = await invoke<{ id: string; planName: string }>("create_duty_plan", { input: { planName: newPlanName } }); setValidationError(""); setPlanId(plan.id); setPlanName(plan.planName); setMessage("已建立計畫。點擊地圖可新增勤務點位。"); } catch (error) { setMessage(`無法建立勤務計畫：${String(error)}`); } }
  function exitPlan() { setPlanId(null); setPlanName("尚未開啟勤務計畫"); setNewPlanName(""); setPoints([]); setPendingCoordinate(null); setActiveNav("勤務計畫"); setMessage("請輸入勤務計畫名稱以建立新計畫。"); }
  function selectPointLocation(latitude: number, longitude: number) { if (!planId) { setMessage("請先建立勤務計畫，再新增點位。"); return; } if (isDrawingRoute) { setManualVertices((current) => [...current, [longitude, latitude]]); setMessage("已加入路線節點；按 Enter 完成，Backspace 復原。 "); return; } if (activeNav !== "點位") { setMessage("請先從左側選擇「點位」，再於地圖新增勤務點位。"); return; } if (selectedPointId) { setSelectedPointId(null); setMessage("已取消選取勤務點位。"); return; } setPendingCoordinate({ latitude, longitude }); setMessage("已選取地圖位置；請填寫點位編號與名稱後保存。"); }
  function addManualVertex(latitude: number, longitude: number) { setManualVertices((current) => [...current, [longitude, latitude]]); setMessage("已加入路線節點；按 Enter 完成，Backspace 復原。"); }
  async function createPoint() { if (!planId || !pendingCoordinate) return; if (!pointCode.trim() || !pointName.trim()) { setValidationError("請輸入點位編號與崗哨位置。"); return; } try { const point = await invoke<MapDutyPoint>("create_duty_point", { input: { planId, pointCode, pointName, color: pointColor, ...pendingCoordinate } }); setValidationError(""); setPoints((current) => [...current, point]); setPendingCoordinate(null); setPointCode(/^\d+$/.test(point.pointCode) ? String(Number(point.pointCode) + 1) : ""); setPointName(""); setMessage(`已保存點位 ${point.pointCode}。`); } catch (error) { setMessage(String(error)); } }
  async function deletePoint() { if (!pendingDelete) return; try { await invoke("delete_duty_point", { pointId: pendingDelete.id }); setPoints((current) => current.filter((item) => item.id !== pendingDelete.id)); setSelectedPointId(null); setMessage(`已刪除點位 ${pendingDelete.pointCode}。`); setPendingDelete(null); } catch (error) { setMessage(String(error)); } }
  async function movePoint(point: MapDutyPoint, latitude: number, longitude: number) { try { await invoke("move_duty_point", { pointId: point.id, latitude, longitude }); setPoints((current) => current.map((item) => item.id === point.id ? { ...item, latitude, longitude } : item)); setMessage(`已移動點位 ${point.pointCode}；相關路線將在建立後標記為需重算。`); } catch (error) { setMessage(String(error)); } }
  function toggleRoutePoint(pointId: string) { setRoutePointIds((current) => current.includes(pointId) ? current.filter((id) => id !== pointId) : [...current, pointId]); }
  async function createRoute() { if (!planId) return; if (!routeName.trim() || routePointIds.length < 2) { setValidationError("請輸入路線名稱，並至少選擇兩個點位。"); return; } try { const route = await invoke<DutyRoute>("create_duty_route", { input: { planId, routeName, color: routeColor, pointIds: routePointIds } }); setValidationError(""); setRoutes((current) => [...current, { ...route, lineStyle: routeLineStyle }]); setRouteName(""); setRoutePointIds([]); setMessage(`已保存路線 ${route.routeName}。`); } catch (error) { setMessage(String(error)); } }
  async function deleteRoute(route: DutyRoute) { try { await invoke("delete_duty_route", { routeId: route.id }); setRoutes((current) => current.filter((item) => item.id !== route.id)); if (selectedRouteId === route.id) setSelectedRouteId(null); if (editingRouteId === route.id) setEditingRouteId(null); setMessage(`已刪除路線 ${route.routeName}。`); } catch (error) { setMessage(String(error)); } }
  async function updateRouteColor(color: string) { setRouteColor(color); const route = routes.find((item) => item.id === selectedRouteId); if (!route) return; const previousColor = route.color; setRoutes((current) => current.map((item) => item.id === route.id ? { ...item, color } : item)); try { await invoke("update_duty_route_color", { routeId: route.id, color }); setMessage(`已更新路線 ${route.routeName} 的顏色。`); } catch (error) { setRoutes((current) => current.map((item) => item.id === route.id ? { ...item, color: previousColor } : item)); setRouteColor(previousColor); setMessage(`無法更新路線顏色：${String(error)}`); } }
  function routeCoordinates(route: DutyRoute) { return route.geometry ?? route.pointIds.map((id) => points.find((point) => point.id === id)).filter((point): point is MapDutyPoint => Boolean(point)).map((point) => [point.longitude, point.latitude] as [number, number]); }
  async function saveSelectedRouteAsCommon() { const route = routes.find((item) => item.id === selectedRouteId); if (!route) { setValidationError("請先選擇一條已儲存路線。"); return; } const geometry = routeCoordinates(route); if (geometry.length < 2) { setValidationError("此路線缺少可用節點，無法儲存為常用路線。"); return; } try { const commonRoute = await invoke<CommonRoute>("create_common_route", { input: { routeName: route.routeName, color: route.color, geometry } }); setCommonRoutes((current) => [commonRoute, ...current]); setValidationError(""); setMessage(`已將 ${route.routeName} 儲存為常用路線。`); } catch (error) { setMessage(`無法儲存常用路線：${String(error)}`); } }
  async function applyCommonRoute(commonRoute: CommonRoute) { if (!planId) { setMessage("請先建立勤務計畫，再套用常用路線。"); return; } try { const route = await invoke<DutyRoute>("create_manual_route", { input: { planId, routeName: commonRoute.routeName, color: commonRoute.color, geometry: commonRoute.geometry } }); setRoutes((current) => [...current, { ...route, lineStyle: "solid" }]); setMessage(`已套用常用路線 ${commonRoute.routeName}。`); } catch (error) { setMessage(`無法套用常用路線：${String(error)}`); } }
  async function deleteCommonRoute(commonRoute: CommonRoute) { try { await invoke("delete_common_route", { routeId: commonRoute.id }); setCommonRoutes((current) => current.filter((item) => item.id !== commonRoute.id)); setMessage(`已刪除常用路線 ${commonRoute.routeName}。`); } catch (error) { setMessage(`無法刪除常用路線：${String(error)}`); } }
  async function assignPersonnel(person: Personnel) { if (!planId || !selectedPointId) { setValidationError("請先在地圖選擇要配置的勤務點位。"); return; } const routeKeys = (pointId: string | null) => { const memberships = routes.filter((route) => pointId && route.pointIds.includes(pointId)).map((route) => route.id); return memberships.length ? memberships : [`point:${pointId ?? "unassigned"}`]; }; const selectedRouteKeys = routeKeys(selectedPointId); const existing = personnelAssignments.find((assignment) => assignment.personnelId === person.id && routeKeys(assignment.dutyPointId).some((key) => selectedRouteKeys.includes(key))); try { if (existing) { await invoke("move_personnel_assignment", { assignmentId: existing.id, dutyPointId: selectedPointId }); setPersonnelAssignments((current) => current.map((assignment) => assignment.id === existing.id ? { ...assignment, dutyPointId: selectedPointId } : assignment)); setMessage(`已將 ${person.name} 移至目前勤務點位。`); } else { const assignment = await invoke<PersonnelAssignment>("create_personnel_assignment", { input: { planId, personnelId: person.id, dutyPointId: selectedPointId, assignedUnit: person.unit, assignedTitle: person.title } }); setPersonnelAssignments((current) => [...current, assignment]); setMessage(`已將 ${person.name} 配置至勤務點位。`); } setValidationError(""); } catch (error) { setMessage(`無法配置人員：${String(error)}`); } }
  async function removePersonnelAssignment(assignment: PersonnelAssignment) { try { await invoke("delete_personnel_assignment", { assignmentId: assignment.id }); setPersonnelAssignments((current) => current.filter((item) => item.id !== assignment.id)); setMessage("已移除人力配置。"); } catch (error) { setMessage(`無法移除人力配置：${String(error)}`); } }
  async function importPersonnelFile(file: File) { try { const fileData = Array.from(new Uint8Array(await file.arrayBuffer())); const result = await invoke<{ totalRows: number; acceptedRows: number; rejectedRows: number }>("import_personnel_xlsx", { input: { fileName: file.name, fileData } }); setPersonnel(await invoke<Personnel[]>("list_personnel")); setMessage(`人力匯入完成：${result.acceptedRows}/${result.totalRows} 筆成功，${result.rejectedRows} 筆拒絕。`); } catch (error) { setMessage(`無法人力匯入：${String(error)}`); } }
  function beginRouteRename(route: DutyRoute) { setSelectedRouteId(route.id); setRouteColor(route.color); setEditingRouteId(route.id); setEditingRouteName(route.routeName); }
  async function saveRouteRename(route: DutyRoute) { const routeName = editingRouteName.trim(); if (!routeName) { setValidationError("請輸入路線名稱。"); return; } try { await invoke("update_duty_route_name", { routeId: route.id, routeName }); setRoutes((current) => current.map((item) => item.id === route.id ? { ...item, routeName } : item)); setEditingRouteId(null); setValidationError(""); setMessage(`已更名為 ${routeName}。`); } catch (error) { setMessage(`無法更新路線名稱：${String(error)}`); } }
  const units = [...new Set(personnel.map((person) => person.unit))].sort();
  const titles = [...new Set(personnel.map((person) => person.title))].sort();
  const selectedPoint = points.find((point) => point.id === selectedPointId);
  const filteredPersonnel = personnel.filter((person) => { const keyword = personnelKeyword.trim().toLowerCase(); return (!keyword || [person.name, person.personnelCode, person.radioCode].some((value) => value.toLowerCase().includes(keyword))) && (!personnelUnit || person.unit === personnelUnit) && (!personnelTitle || person.title === personnelTitle); });
  const pointAssignments = personnelAssignments.filter((assignment) => assignment.dutyPointId === selectedPointId);
  const personnelLabels = personnelAssignments.reduce<Record<string, string[]>>((labels, assignment) => { if (!assignment.dutyPointId) return labels; const person = personnel.find((item) => item.id === assignment.personnelId); if (person) (labels[assignment.dutyPointId] ??= []).push(person.name); return labels; }, {});
  const sameCodeAssignments = selectedPoint ? personnelAssignments.filter((assignment) => { const point = points.find((item) => item.id === assignment.dutyPointId); return point && point.id !== selectedPoint.id && point.pointCode === selectedPoint.pointCode && point.color !== selectedPoint.color; }) : [];
  const preferredPersonnelIds = new Set(sameCodeAssignments.map((assignment) => assignment.personnelId));
  const prioritizedPersonnel = [...filteredPersonnel].sort((left, right) => Number(preferredPersonnelIds.has(right.id)) - Number(preferredPersonnelIds.has(left.id)) || left.personnelCode.localeCompare(right.personnelCode));
  async function saveManualRoute() { if (!planId) return; if (!routeName.trim() || manualVertices.length < 2) { setValidationError("請輸入路線名稱，並至少繪製兩個折點。"); return; } try { const route = await invoke<DutyRoute>("create_manual_route", { input: { planId, routeName, color: routeColor, geometry: manualVertices } }); setValidationError(""); setRoutes((current) => [...current, { ...route, lineStyle: routeLineStyle }]); setManualVertices([]); setRouteName(""); setMessage(`已保存手繪路線 ${route.routeName}。`); } catch (error) { setMessage(String(error)); } }
  const deploymentRows = points.map((point, index) => {
    const assignments = personnelAssignments.filter((assignment) => assignment.dutyPointId === point.id);
    const assignedPeople = assignments.map((assignment) => personnel.find((person) => person.id === assignment.personnelId)).filter((person): person is Personnel => Boolean(person));
    return { index: index + 1, point, units: [...new Set(assignments.map((assignment) => assignment.assignedUnit))].join("／") || "—", count: assignedPeople.length, names: assignedPeople.map((person) => `${person.title}\n${person.name}\n${person.phone}`).join("\n\n") || "—", radios: assignedPeople.map((person) => person.radioCode).join("\n") || "—" };
  });
  function downloadBlob(blob: Blob, fileName: string) { const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = fileName; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); }
  function exportMapImage() { const image = mapExporter.current?.(); if (!image) { setMessage("地圖尚未完成載入，請稍候再匯出。 "); return; } const anchor = document.createElement("a"); anchor.href = image; anchor.download = `${planName || "DutyGrid"}-勤務地圖.png`; anchor.click(); setMessage("已下載勤務地圖 PNG。 "); }
  async function exportDeploymentTable() { try { const bytes = await invoke<number[]>("export_deployment_xlsx", { input: { planName, rows: deploymentRows.map((row) => ({ sequence: row.index, pointName: row.point.pointName, unit: row.units === "—" ? "" : row.units, policeCount: row.count, personnelText: row.names === "—" ? "" : row.names, radioText: row.radios === "—" ? "" : row.radios })) } }); downloadBlob(new Blob([new Uint8Array(bytes)], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }), `${planName || "DutyGrid"}-安全維護部署表.xlsx`); setMessage("已匯出安全維護部署表。 "); } catch (error) { setMessage(`無法匯出安全維護部署表：${String(error)}`); } }
  return (
    <main className={activeNav === "部署表" ? "app-shell preview-mode" : "app-shell"}>
      <header className="top-bar">
        <strong>DutyGrid</strong>
        <span className="plan-name">{planName}</span>
        <div className="top-actions">
          <button type="button" disabled>儲存</button>
          <button type="button" disabled={activeNav !== "部署表"} onClick={() => void exportDeploymentTable()}>匯出</button>
        </div>
      </header>
      <aside className="sidebar" aria-label="主要導覽">
        {navigation.map((item) => <button className={activeNav === item ? "nav-item active" : "nav-item"} key={item} type="button" onClick={() => { setActiveNav(item); if (item !== "點位") setPendingCoordinate(null); if (item === "人力配置") setMessage("請先在地圖點選勤務點位，再從下方篩選並配置人員。"); else if (item === "部署表") setMessage("此預覽為「安全維護部署表」第一頁的欄位；正式匯出將自第 7 列開始填入。點選表格列可定位地圖點位。"); else if (item === "路線") setMessage("請選擇已儲存路線，或開始繪製新的勤務路線。"); else if (item === "點位") setMessage("請在地圖點選位置以新增勤務點位。"); else if (item === "未實作功能") setMessage("此功能頁尚未開始實作。"); }}>{item}</button>)}
      </aside>
      <section className="workspace" aria-label="地圖工作區">
        <MapCanvas isDrawingRoute={isDrawingRoute} manualVertexColor={routeColor} manualVertices={manualVertices} onExportReady={(exporter) => { mapExporter.current = exporter; }} onMapClick={selectPointLocation} onPendingCancel={() => { setPendingCoordinate(null); setMessage("已取消放置暫存點位。"); }} onPointMoved={movePoint} onPointSelect={setSelectedPointId} onRouteVertex={addManualVertex} pendingColor={pointColor} pendingCoordinate={pendingCoordinate} personnelLabels={personnelLabels} points={points} routeLines={[...routes.map((route) => ({ color: route.color, dashed: route.lineStyle === "dashed", coordinates: routeCoordinates(route) })), ...(manualVertices.length > 1 ? [{ color: routeColor, coordinates: manualVertices, dashed: routeLineStyle !== "solid", opacity: 0.45 }] : [])].filter((route) => route.coordinates.length > 1)} selectedPointId={selectedPointId} showPersonnelLabels={showPersonnelLabels} />
        {activeNav === "部署表" && <div className="map-preview-note">此預覽為「安全維護部署表」第一頁的欄位；正式匯出將自第 7 列開始填入。點選表格列可定位地圖點位。</div>}
        <div className="map-label-actions"><button type="button" onClick={(event) => { const showing = event.currentTarget.dataset.visible === "true"; document.querySelectorAll(".duty-point-dot").forEach((element) => element.classList.toggle("show-label", !showing)); event.currentTarget.dataset.visible = String(!showing); event.currentTarget.textContent = showing ? "顯示標籤" : "隱藏標籤"; }}>顯示標籤</button></div>
        {activeNav === "人力配置" && <div className="map-personnel-actions"><button type="button" onClick={() => setShowPersonnelLabels((value) => !value)}>{showPersonnelLabels ? "隱藏人力" : "顯示人力"}</button></div>}
        {activeNav === "路線" && <div className="map-route-colors" aria-label="路線顏色">{pointColors.map((color) => <button aria-label={color.label} className={`color-option ${color.value} ${routeColor === color.value ? "selected" : ""}`} key={color.value} type="button" onClick={() => void updateRouteColor(color.value)} />)}</div>}
        {activeNav === "路線" && <div className="map-line-style"><button className={routeLineStyle === "solid" ? "active" : ""} type="button" onClick={() => setRouteLineStyle("solid")}>實線</button><button className={routeLineStyle === "dashed" ? "active" : ""} type="button" onClick={() => setRouteLineStyle("dashed")}>虛線</button><button type="button" onClick={() => { setIsDrawingRoute((value) => !value); setMessage(isDrawingRoute ? "已完成繪製；請保存路線。" : "繪製模式：點擊地圖加入折點；空白鍵復原。 "); }}>{isDrawingRoute ? "完成繪製" : "開始繪製"}</button></div>}
      </section>
      <aside className={activeNav === "路線" ? "inspector route-inspector" : activeNav === "人力配置" ? "inspector personnel-inspector" : "inspector"} aria-label="詳細資料面板" onClick={(event) => { if (event.target === event.currentTarget) { setSelectedPointId(null); setSelectedRouteId(null); } }}>
        <h1>{activeNav === "點位" ? "勤務點位" : activeNav === "路線" ? "勤務路線" : activeNav === "人力配置" ? "人力配置" : activeNav === "部署表" ? "安全維護部署表預覽" : activeNav === "未實作功能" ? "未實作功能" : planId ? "勤務計畫" : "開始建立勤務計畫"}</h1>
        {activeNav !== "部署表" && <p>{message}</p>}
        {validationError && <p className="validation-error" role="alert">{validationError}</p>}
        {!planId && activeNav === "勤務計畫" && <form onSubmit={(event) => { event.preventDefault(); void createPlan(); }}><label className="field-label" htmlFor="plan-name">勤務計畫名稱</label><input id="plan-name" value={newPlanName} onChange={(event) => { setNewPlanName(event.target.value); setPlanName(event.target.value.trim() || "尚未開啟勤務計畫"); }} /><button type="submit">新增勤務計畫</button></form>}
        {planId && activeNav === "勤務計畫" && <section className="plan-summary"><span>目前開啟</span><strong>{planName}</strong><p>請由左側選擇「點位」以新增、查看或刪除勤務點位。</p><button className="secondary-button" type="button" onClick={exitPlan}>退出勤務計畫</button></section>}
        {activeNav === "點位" && <><div className="point-list">{points.length ? points.map((point) => <div className="point-list-row" key={point.id}><button className={selectedPointId === point.id ? "point-list-item selected" : "point-list-item"} type="button" onClick={() => setSelectedPointId(point.id)}><i className={`point-color-chip ${point.color}`} />{point.pointCode}｜{point.pointName}</button><button className="delete-button" type="button" onClick={() => setPendingDelete(point)}>刪除</button></div>) : <p>尚無勤務點位。請在地圖點擊位置新增。</p>}</div>{pendingCoordinate && <form onSubmit={(event) => { event.preventDefault(); void createPoint(); }}><h2>新增勤務點位</h2><p>{pendingCoordinate.latitude.toFixed(5)}, {pendingCoordinate.longitude.toFixed(5)}</p><label className="field-label">點位編號</label><input value={pointCode} onChange={(event) => setPointCode(event.target.value)} /><label className="field-label">點位名稱（崗哨位置）</label><input value={pointName} onChange={(event) => setPointName(event.target.value)} /><label className="field-label">點位顏色</label><div className="color-options">{pointColors.map((color) => <button aria-label={color.label} className={`color-option ${color.value} ${pointColor === color.value ? "selected" : ""}`} key={color.value} type="button" onClick={() => setPointColor(color.value)} />)}</div><button type="submit">保存點位</button></form>}</>}
        {activeNav === "路線" && <>
          <p>按「開始繪製」後，依序點擊地圖：兩點即成直線，繼續點擊可新增折點。空白鍵復原最後一點。</p>
          {routes.length > 0 && <><span className="section-caption">已儲存路線</span><div className="route-list">{routes.map((route) => <div className={selectedRouteId === route.id ? "route-list-row selected" : "route-list-row"} key={route.id} onContextMenu={(event) => { event.preventDefault(); beginRouteRename(route); }}>{editingRouteId === route.id ? <form className="route-rename-form" onSubmit={(event) => { event.preventDefault(); void saveRouteRename(route); }}><i className={`point-color-chip ${route.color}`} /><input autoFocus aria-label="路線名稱" value={editingRouteName} onChange={(event) => setEditingRouteName(event.target.value)} onKeyDown={(event) => { if (event.key === "Escape") { setEditingRouteId(null); setEditingRouteName(""); } }} /></form> : <button className="route-list-select" type="button" onClick={() => { setSelectedRouteId(route.id); setRouteColor(route.color); setMessage(`已選取路線 ${route.routeName}；可由地圖色盤變更顏色。`); }} onDoubleClick={() => beginRouteRename(route)}><i className={`point-color-chip ${route.color}`} />{route.routeName}</button>}<button className="route-delete-button" aria-label={`刪除 ${route.routeName}`} type="button" onClick={() => void deleteRoute(route)}>×</button></div>)}</div>{selectedRouteId && <button className="save-common-route" type="button" onClick={() => void saveSelectedRouteAsCommon()}>儲存為常用路線</button>}</>}
          <form onSubmit={(event) => { event.preventDefault(); void saveManualRoute(); }}><label className="field-label">路線名稱</label><div className="route-name-row"><input value={routeName} onChange={(event) => setRouteName(event.target.value)} /><button type="submit">保存</button></div><label className="field-label">路線顏色</label><div className="color-options">{pointColors.map((color) => <button aria-label={color.label} className={`color-option ${color.value} ${routeColor === color.value ? "selected" : ""}`} key={color.value} type="button" onClick={() => setRouteColor(color.value)} />)}</div><div className="drawing-actions"><button type="button" onClick={() => { setIsDrawingRoute((value) => !value); setMessage(isDrawingRoute ? "已完成繪製；請保存路線。" : "繪製模式：點擊地圖加入折點；空白鍵復原。 "); }}>{isDrawingRoute ? "完成繪製" : "開始繪製"}</button></div></form>
          <section className="point-route-placeholder"><strong>依點位建立路線</strong><span>功能尚未實作</span></section>
          <section className="common-route-history"><strong>已儲存歷史路線</strong>{commonRoutes.length ? <div className="route-list">{commonRoutes.map((route) => <div className="route-list-row" key={route.id}><button className="route-list-select" type="button" onClick={() => void applyCommonRoute(route)}><i className={`point-color-chip ${route.color}`} />{route.routeName}</button><button className="route-delete-button" aria-label={`刪除常用路線 ${route.routeName}`} type="button" onClick={() => void deleteCommonRoute(route)}>×</button></div>)}</div> : <span>尚無常用路線。</span>}</section>
        </>}
        {activeNav === "人力配置" && <><p>{selectedPoint ? `目前配置點位：${selectedPoint.pointCode}｜${selectedPoint.pointName}` : "請先在地圖點選勤務點位，再從下方篩選並配置人員。"}</p><section className="personnel-import"><strong>匯入人力資料</strong><span>接受 .xlsx。必填欄位：personnel_code、radio_code、name、title、unit、phone。</span><input accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" type="file" onChange={(event) => { const file = event.target.files?.[0]; if (file) void importPersonnelFile(file); event.currentTarget.value = ""; }} /></section><div className="personnel-filters"><input aria-label="搜尋人員" placeholder="搜尋姓名、警號或無線電代號" value={personnelKeyword} onChange={(event) => setPersonnelKeyword(event.target.value)} /><select aria-label="篩選單位" value={personnelUnit} onChange={(event) => setPersonnelUnit(event.target.value)}><option value="">所有單位</option>{units.map((unit) => <option key={unit} value={unit}>{unit} 單位</option>)}</select><select aria-label="篩選職稱" value={personnelTitle} onChange={(event) => setPersonnelTitle(event.target.value)}><option value="">所有職稱</option>{titles.map((title) => <option key={title} value={title}>{title}</option>)}</select></div>{selectedPoint && <section className="assigned-personnel"><strong>已配置人員（{pointAssignments.length}）</strong>{pointAssignments.length ? pointAssignments.map((assignment) => { const person = personnel.find((item) => item.id === assignment.personnelId); return <div className="assignment-row" key={assignment.id}><span>{person?.name ?? "已刪除人員"} · {assignment.assignedTitle}</span><button type="button" onClick={() => void removePersonnelAssignment(assignment)}>移除</button></div>; }) : <span>尚未配置人員。</span>}</section>}<section className="personnel-results"><strong>可配置人員（{prioritizedPersonnel.length}）</strong><div className="personnel-scroll">{prioritizedPersonnel.map((person) => { const assignedAtPoint = personnelAssignments.some((assignment) => assignment.personnelId === person.id && assignment.dutyPointId === selectedPointId); const preferredAssignment = sameCodeAssignments.find((assignment) => assignment.personnelId === person.id); const preferredPoint = points.find((point) => point.id === preferredAssignment?.dutyPointId); return <div className={preferredPersonnelIds.has(person.id) ? "personnel-row preferred" : "personnel-row"} key={person.id}><span><b>{person.name}{preferredPoint && <em>已配置於 {preferredPoint.color} 色 {preferredPoint.pointCode}</em>}</b><small>{person.personnelCode} · {person.radioCode} · {person.unit} 單位 · {person.title}</small></span><button disabled={!selectedPoint || assignedAtPoint} type="button" onClick={() => void assignPersonnel(person)}>{assignedAtPoint ? "已配置" : "配置"}</button></div>; })}</div></section></>}
        {activeNav === "部署表" && <section className="deployment-preview"><div className="deployment-export-actions"><button type="button" onClick={exportMapImage}>匯出地圖 PNG</button><button type="button" onClick={() => void exportDeploymentTable()}>匯出安全維護部署表</button></div><div className="a4-preview"><h2>安全維護部署表</h2><p>勤務計畫：{planName}</p><p>勤務日期：________________　勤務時間：________________　承辦單位：________________</p><table><thead><tr><th>編號</th><th>崗哨別</th><th>崗哨位置</th><th>派遣單位</th><th>警力</th><th>職稱姓名</th><th>無線電代號</th><th>服裝及應勤裝備</th><th>分（協調）區協調員電話</th></tr></thead><tbody>{deploymentRows.map((row) => <tr className={selectedPointId === row.point.id ? "selected" : ""} key={row.point.id} onClick={() => { setSelectedPointId(row.point.id); setMessage(`已定位勤務點位：${row.point.pointCode}｜${row.point.pointName}`); }}><td>{row.index}</td><td>—</td><td>{row.point.pointName}</td><td>{row.units}</td><td>{row.count}</td><td>{row.names}</td><td>{row.radios}</td><td>制服、無線電</td><td>—</td></tr>)}</tbody></table></div></section>}
        {activeNav === "未實作功能" && <p>此分頁預留給後續功能，目前尚未實作。</p>}
      </aside>
      <footer className="status-bar">資料庫：尚未初始化　｜　路口參考：已隨 App 提供</footer>
      {pendingDelete && <div className="confirm-backdrop" role="dialog" aria-modal="true"><section className="confirm-dialog"><h2>刪除勤務點位？</h2><p>將永久刪除「{pendingDelete.pointCode}｜{pendingDelete.pointName}」。</p><div><button type="button" onClick={() => setPendingDelete(null)}>取消</button><button className="delete-button" type="button" onClick={() => void deletePoint()}>確認刪除</button></div></section></div>}
    </main>
  );
}
